AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ip-locator

  SAM Template for ip-locator

Globals:
  Function:
    Timeout: 3

Resources:
  IPLocatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: iplocator/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        IPLocator:
          Type: Api
          Properties:
            Path: /ip-locator
            Method: get

Outputs:
  IPLocatorApi:
    Description: "API Gateway endpoint URL for Prod stage for IPLocator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ip-locator/"
  IPLocatorFunction:
    Description: "IPLocator Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  IPLocatorIamRole:
    Description: "Implicit IAM Role created for IPLocator function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
